# Generated by Django 3.2.9 on 2021-11-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendshiprequest',
            old_name='accept',
            new_name='accepted',
        ),
    ]
