# Generated by Django 3.2.9 on 2021-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_auto_20211122_1134'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_account_profile_friends_+', through='friendship.Friends', to='account.Profile'),
        ),
    ]
