# Generated by Django 3.2.9 on 2021-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211107_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicstatus',
            name='status_text',
            field=models.CharField(max_length=250),
        ),
    ]
